# src/Ais/KontrakMahasiswaBundle/Resources/config/validation.yml
Ais\KontrakMahasiswaBundle\Entity\KontrakMahasiswa:
    properties:
        mahasiswa_id:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 2
                max: 100
                minMessage: "Your title must be at least {{ limit }} characters length"
                maxMessage: "Your title name cannot be longer than {{ limit }} characters length"
