<?php

namespace Ais\KontrakMahasiswaBundle\Repository;

/**
 * KontrakMahasiswaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KontrakMahasiswaRepository extends \Doctrine\ORM\EntityRepository
{
}
